[package]
name = "gist"
description = "A simple Github Gist client"
version = "0.4.0"
authors = ["Arnaud Berthomier <oz@lespepitos.org>"]
license = "MIT"
repository = "https://github.com/lespepitos/gist"

[[bin]]
name = "gist"
path = "src/main.rs"

[dependencies]
getopts = "0.2"
rustc-serialize = "0.3"
hyper = "0.8"
