[package]
name = "gist"
description = "A simple Github Gist client"
version = "0.4.2"
authors = ["Arnaud Berthomier <oz@lespepitos.org>"]
license = "MIT"
repository = "https://github.com/lespepitos/gist"

[[bin]]
name = "gist"
path = "src/main.rs"

[dependencies]
getopts = "0.2"
hyper = "0.9"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
