[package]
name = "gist"
description = "A simple Github Gist client"
version = "0.4.3"
authors = ["Arnaud Berthomier <oz@lespepitos.org>"]
license = "MIT"
repository = "https://github.com/lespepitos/gist"
readme = "README.md"

[[bin]]
name = "gist"
path = "src/bin/gist/main.rs"

[dependencies]
getopts = "~0.2"
reqwest = "~0.7"
error-chain = "~0.11"
serde = "~1.0"
serde_json = "~1.0"
serde_derive = "~1.0"
